# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：info，级别越高日志输出量越大，越倾向于调试)
# 四个级别：silent / info / warning / error / debug
log-level: info

# Clash 的 RESTful API
external-controller: 127.0.0.1:9090

# DNS 设置
dns:
  enable: false # set true to enable dns (default is false)

# Clash for Windows
# Proxies module latency test settings
cfw-latency-timeout: 3000
cfw-latency-url: http://www.gstatic.com/generate_204

# 代理节点
proxies:
- name: ss-aws-singapore
  type: ss
  server: 52.221.207.107
  port: 38888
  password: abc12345
  cipher: chacha20-ietf-poly1305
  udp: true
- name: ss2
  type: ss
  server: 52.221.207.107
  port: 38888
  password: abc12345
  cipher: chacha20-ietf-poly1305
  udp: true

# 代理组策略
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - ss-aws-singapore
  - ss2
- name: Hijacking
  type: select
  proxies:
  - DIRECT
  - REJECT
  - PROXY
- name: FINAL
  type: select
  proxies:
  - PROXY
  - DIRECT


# 规则
rules:
# CUSTOM

# Internet Service Provider Hijacking Protection 运营商劫持保护
- DOMAIN-SUFFIX,ip138.com,PROXY
- MATCH,PROXY
